import { Inter } from "next/font/google";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import 'bootstrap/dist/css/bootstrap.css'
import Bootstrapjs from '@/app/components/bootstrapjs/Bootstrapjs'

import '../app/scss/style.scss';
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <Header/>
        {children}
        <Bootstrapjs/>
        <Footer/>
        </body>
    </html>
  );
}
